New workflow file to demonstrate matrices - UPDATES

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -6,16 +6,38 @@ jobs:
   backward-compatibility:
     # Specifies the runner environment where the job will execute.
     runs-on: ${{ matrix.operating-system }}
-    name: ${{ matrix.node-version }} - ${{ matrix.operating-system }}
+    name: ${{ matrix.operating-system }} - ${{ matrix.node-version }}
     strategy:
+      # fail-fast: Determines whether to cancel all in-progress jobs if any matrix job fails.
+      # When set to true, GitHub will cancel all running jobs as soon as one job fails.
+      # This helps save resources and CI/CD minutes by stopping unnecessary builds when an error is detected.
+      # Set to false if you want all matrix jobs to complete regardless of individual failures.
+      # fail-fast Documentation
+      # The default value for fail-fast is true, meaning that if any job in the matrix fails, all other jobs that are still running will be cancelled immediately. Setting fail-fast to false allows all jobs to run to completion even if one or more jobs fail.
+      fail-fast: true
       matrix:
         node-version: [18.x, 20.x, 21.x]
         operating-system: [ubuntu-latest, windows-latest]
+        # The 'include' keyword allows you to add specific job configurations to a matrix strategy.
+        # It enables you to include additional combinations that might not be generated by the standard matrix expansion.
+        # Use case: Add a specific Node.js version (16.x) on Ubuntu that you want to test in addition to other matrix combinations,
+        # or run a particular configuration that differs from your standard matrix parameters.
+        include:
+          - node-version: 16.x
+            operating-system: ubuntu-latest
+          - node-version: 21.x
+            operating-system: ubuntu-latest
+            tag: experimental
     steps:
       - name: Setup node
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
+      - name: Fail if experimental tag is present
+        if: ${{ matrix.tag == 'experimental' }}
+        run: |
+          echo "This is an experimental configuration. Failing the job intentionally."
+          exit 1
       - name: Perform some tests
         run: |
           echo "Running tests on OS ${{ matrix.operating-system }} and NodeJS ${{ matrix.node-version }}"
